-- MySQL Script generated by MySQL Workbench
-- Tue Feb  5 15:14:16 2019
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projetoTeste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoTeste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoTeste` ;
USE `projetoTeste` ;

-- -----------------------------------------------------
-- Table `projetoTeste`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoTeste`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL,
  `senha` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoTeste`.`artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoTeste`.`artigos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NULL,
  `link` VARCHAR(150) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_artigos_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_artigos_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `projetoTeste`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO usuario VALUES(1, 'admin', 'admin')

ENGINE = InnoDB;

INSERT INTO artigos VALUES(1, 'ArtigoTeste','https://artigoteste.com.br/',1),
(2, 'ArtigoTeste','https://artigoteste.com.br/',1),
(3, 'ArtigoTeste','https://artigoteste.com.br/',1)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

